### ISSUE TITLE
run fails

### ISSUE THREAD

**Issue by alyahmedaly** [deebloo/wireit-visualizer#8]
when running on our monorepo I got 
![image](https://github.com/deebloo/wireit-visualizer/assets/6495633/15d0c193-b835-478e-bf5a-ac78b4e81fee)

not sure how can I share more details

**Comment by alyahmedaly** [comment]
looks like it's related to mermaid I tried the logged graph with mermaid and I got `Error: Evaluation failed: Error: Too many edges`

**Comment by deebloo** [comment]
did it work when you launched the local server?

**Comment by deebloo** [comment]
Also I am assuming you can't share either the repo or the graph itself?

**Comment by alyahmedaly** [comment]
yes, it will be hard to share, it's clear the issue is not `wireit-visualizer` my graph is so big 800 line 😄  I think it's related to how wireit was designed I might open issue for wireit to improve the analyzer as I'm sure the output graph is not what is executed at the end or maybe it's which is huge

**Comment by deebloo** [comment]
I think it is probably an issue with mermaid if anything. QQ though. can you try opening the local server with a specific package task passed in? Will at least help me narrow down where an issue might be

http://localhost:4200/?task=packages/my-package:test

**Comment by alyahmedaly** [comment]
@deebloo sorry for late reply, it's an issue with mermaid my graph is too big and was able to render it with another dot graph, but  I still like your tool so much I think you can look at this discussion might be relevant as well https://discord.com/channels/1036766782867914792/1183832842120220802/1183832842120220802
