### ISSUE TITLE
Alterative to Mermaid

### ISSUE THREAD

**Issue by deebloo** [deebloo/wireit-visualizer#9]
It seems that there is a node limit for mermaid. Will take a look at other graph options

**Comment by alyahmedaly** [comment]
if you check this PR Wireit might support Graphviz as well https://github.com/google/wireit/commit/d1aed2fe859c5d1e45f17100954d42e9e25b63b5#diff-940e3850dd4ed0916f6f1d4da40fbb8fd5be5f0ac0c826437d5a39c0468fb020R57

**Comment by deebloo** [comment]
Graphvis was my next choice! Excellent
